spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway
  mvc:
    view:
      suffix: .html

server:
  port: 8765

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  prefix: /api
  routes:
    service1:
      path: /service1/**
      serviceId: service1
    service2:
      path: /service2/**
      serviceId: service2
    mediator:
      path: /mediator/**
      serviceId: mediator

security:
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://uaa-service/oauth/token
      clientId: example_id
      clientSecret: example_secret
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhr48B5ICsfOIfd4S/+x1j+pKpLcxKsiiF1J7jbZeneTRMKL+peZCnrvLCqKAODyir5AyYKqv8T1PnczfOceif+zKJ0cTr4Lmz7I0P1lEhakpjJIxAGtWktPtKWX3ZK7uX8galzOYhcWeOPYL+MJIUSkwRA2pdIsjC8wf/6qIaz19C8URNG1ciBirXre5Ambd6guQ5hKKnzWMZdz77lAKbpVK2RRIY6+5r0BR/NxMcn5Lgp7ZzBFA+nwCaqRnKFPbjceKBQzNY7wKut/TvdQCIW6btdU6/WT8IOY5HIOqCAyq/BQmU2jOM0WGhvcl2NOgLI0vdZ1oC0Uu34HG+YgQLwIDAQAB
          -----END PUBLIC KEY-----